name: i18n
description: Simple internationalization tool for Dart and Flutter, based on YAML files and source generation.
version: 0.9.2
homepage: https://github.com/MohiuddinM/i18n
author: Muhammad Mohiuddin <muhammad.mohiuddin@live.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  build: ^1.1.4
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^0.4.0
  yaml: ^2.1.16

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0

